name: GroupSupport
main: demenius.groupsupport.GroupSupport
version: 1.1
commands:
  GroupSupport:
    description: Add The Ability To Create And Modify Groups
    usage: /GroupSupport|gs help For Additional Information
    aliases: [GroupSupport, gs]